permalink: pretty
markdown: kramdown
paginate: 10
exclude: ["Rakefile", "README.markdown"]
url: http://bricksoncentral.com
meta:
    title: Bricks on Central &mdash; Minot, ND
    description: Uniqe historic building in downtown Minot, ND
deploy:
    ssh:
        target: bricksoncentral@bricksoncentral.com
        port: 4668
    remote_path: ~/public_html
